from abc import ABC, abstractmethod
from typing import List
from app.domain.entities import (
    Procedencia,
    Acta,
    ActaGeneracionResiduo,
    Usuario,
    GeneracionResiduo,
    Area,
    CategoriaResiduo,
    ResiduoEspecifico,
    CentroCosto,
    RolAdministrativo,
    Operario
)

class ProcedenciaRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[Procedencia]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Procedencia: ...
    @abstractmethod
    def create(self, entity: Procedencia) -> Procedencia: ...
    @abstractmethod
    def update(self, id: int, entity: Procedencia) -> Procedencia: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...

class AreaRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[Area]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Area: ...
    @abstractmethod
    def create(self, entity: Area) -> Area: ...
    # No update ni delete porque no se modifican ni eliminan las áreas

class CategoriaResiduoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[CategoriaResiduo]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> CategoriaResiduo: ...
    @abstractmethod
    def create(self, entity: CategoriaResiduo) -> CategoriaResiduo: ...
    @abstractmethod
    def update(self, id: int, entity: CategoriaResiduo) -> CategoriaResiduo: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...

class ResiduoEspecificoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[ResiduoEspecifico]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> ResiduoEspecifico: ...
    @abstractmethod
    def create(self, entity: ResiduoEspecifico) -> ResiduoEspecifico: ...
    @abstractmethod
    def update(self, id: int, entity: ResiduoEspecifico) -> ResiduoEspecifico: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...

class OperarioRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[Operario]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Operario: ...
    @abstractmethod
    def create(self, entity: Operario) -> Operario: ...
    @abstractmethod
    def update(self, id: int, entity: Operario) -> Operario: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...

class GeneracionResiduoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[GeneracionResiduo]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> GeneracionResiduo: ...
    @abstractmethod
    def create(self, entity: GeneracionResiduo) -> GeneracionResiduo: ...
    @abstractmethod
    def update(self, id: int, entity: GeneracionResiduo) -> GeneracionResiduo: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...

class CentroCostoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[CentroCosto]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> CentroCosto: ...
    @abstractmethod
    def create(self, entity: CentroCosto) -> CentroCosto: ...
    @abstractmethod
    def update(self, id: int, entity: CentroCosto) -> CentroCosto: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...

class RolAdministrativoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[RolAdministrativo]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> RolAdministrativo: ...
    @abstractmethod
    def create(self, entity: RolAdministrativo) -> RolAdministrativo: ...
    @abstractmethod
    def update(self, id: int, entity: RolAdministrativo) -> RolAdministrativo: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...

class UsuarioRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[Usuario]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Usuario: ...
    @abstractmethod
    def create(self, entity: Usuario) -> Usuario: ...
    @abstractmethod
    def update(self, id: int, entity: Usuario) -> Usuario: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...

class ActaRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[Acta]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Acta: ...
    @abstractmethod
    def create(self, entity: Acta) -> Acta: ...
    @abstractmethod
    def update(self, id: int, entity: Acta) -> Acta: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...

class ActaGeneracionResiduoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[ActaGeneracionResiduo]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> ActaGeneracionResiduo: ...
    @abstractmethod
    def create(self, entity: ActaGeneracionResiduo) -> ActaGeneracionResiduo: ...
    @abstractmethod
    def update(self, id: int, entity: ActaGeneracionResiduo) -> ActaGeneracionResiduo: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...