# Generated by Django 5.2 on 2025-09-17 15:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='GeneracionResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('peso', models.FloatField()),
                ('motivo', models.CharField(blank=True, choices=[('Averia', 'Avería'), ('Bloqueado', 'Bloqueado'), ('Incidente', 'Incidente'), ('Obsoleto', 'Obsoleto'), ('Rechazo', 'Rechazo'), ('Vencido', 'Vencido')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'GeneracionResiduo',
            },
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sede', models.CharField(choices=[('Productora', 'Productora'), ('Comercial', 'Comercial'), ('RioNegro', 'RioNegro')], max_length=20)),
            ],
            options={
                'db_table': 'Procedencia',
            },
        ),
        migrations.CreateModel(
            name='RolAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Gestión Ambiental', 'Gestión Ambiental'), ('Punto Verde', 'Punto Verde')], max_length=50)),
            ],
            options={
                'db_table': 'RolAdministrativo',
            },
        ),
        migrations.CreateModel(
            name='CategoriaResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
            ],
            options={
                'db_table': 'CategoriaResiduo',
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
            ],
            options={
                'db_table': 'CentroCosto',
            },
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(max_length=50, unique=True)),
                ('fecha_acta', models.DateTimeField()),
                ('firma_entrega', models.TextField()),
                ('firma_recepcion', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.centrocosto')),
            ],
            options={
                'db_table': 'Acta',
            },
        ),
        migrations.CreateModel(
            name='ActaGeneracionResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_reportado', models.FloatField()),
                ('peso_conciliado', models.FloatField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acta')),
                ('generacion_residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.generacionresiduo')),
            ],
            options={
                'db_table': 'Acta_GeneracionResiduo',
            },
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
            ],
            options={
                'db_table': 'Operario',
            },
        ),
        migrations.AddField(
            model_name='generacionresiduo',
            name='operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operario'),
        ),
        migrations.AddField(
            model_name='acta',
            name='operario_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas_entregadas', to='app.operario'),
        ),
        migrations.AddField(
            model_name='acta',
            name='operario_recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas_recibidas', to='app.operario'),
        ),
        migrations.AddField(
            model_name='area',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procedencia'),
        ),
        migrations.CreateModel(
            name='ResiduoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriaresiduo')),
            ],
            options={
                'db_table': 'ResiduoEspecifico',
            },
        ),
        migrations.AddField(
            model_name='generacionresiduo',
            name='residuo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.residuoespecifico'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.area')),
                ('rol_administrativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.roladministrativo')),
            ],
            options={
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
