# Generated by Django 5.2 on 2025-04-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('image', models.TextField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gerencia',
            },
        ),
    ]
