# Generated by Django 5.2 on 2025-09-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(unique=True)),
                ('fecha_acta', models.TextField()),
                ('firma_entrega', models.TextField(blank=True, null=True)),
                ('firma_recepcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Acta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActaGeneracionresiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_reportado', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('peso_conciliado', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Acta_GeneracionResiduo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'Area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoriaresiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'CategoriaResiduo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Centrocosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField()),
            ],
            options={
                'db_table': 'CentroCosto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Generacionresiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.TextField()),
                ('peso', models.DecimalField(decimal_places=5, max_digits=10)),
                ('motivo', models.CharField()),
            ],
            options={
                'db_table': 'GeneracionResiduo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('apellido', models.CharField()),
                ('documento', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'Operario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('sede', models.CharField()),
            ],
            options={
                'db_table': 'Procedencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Residuoespecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'ResiduoEspecifico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roladministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'RolAdministrativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamea', models.CharField(db_column='usernameA', unique=True)),
                ('password_hash', models.CharField()),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
    ]
