# Generated by Django 5.2 on 2025-09-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_acta_actageneracionresiduo_area_categoriaresiduo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
