from abc import ABC, abstractmethod
from typing import List, Optional
from app.domain.entities import (
    Procedencia,
    Area,
    SubArea,
    CategoriaResiduo,
    ResiduoEspecifico,
    Operario,
    GeneracionResiduo,
    CentroCosto,
    RolAdministrativo,
    Acta,
    ActaGeneracionResiduo,
)

# ==============================
# REPOSITORIOS ABSTRACTOS (Interfaces)
# ==============================

class ProcedenciaRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[Procedencia]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Optional[Procedencia]: ...
    @abstractmethod
    def create(self, entity: Procedencia) -> Procedencia: ...
    @abstractmethod
    def update(self, id: int, entity: Procedencia) -> Procedencia: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...


class AreaRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[Area]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Optional[Area]: ...
    @abstractmethod
    def create(self, entity: Area) -> Area: ...

class SubAreaRepository(ABC):
    @abstractmethod
    def list_all(self) -> List['SubArea']: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Optional['SubArea']: ...
    @abstractmethod
    def create(self, entity: 'SubArea') -> 'SubArea': ...
    @abstractmethod
    def update(self, id: int, entity: 'SubArea') -> 'SubArea': ...
    @abstractmethod
    def delete(self, id: int) -> None: ...

class CategoriaResiduoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[CategoriaResiduo]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Optional[CategoriaResiduo]: ...
    @abstractmethod
    def create(self, entity: CategoriaResiduo) -> CategoriaResiduo: ...
    @abstractmethod
    def update(self, id: int, entity: CategoriaResiduo) -> CategoriaResiduo: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...


class ResiduoEspecificoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[ResiduoEspecifico]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Optional[ResiduoEspecifico]: ...
    @abstractmethod
    def create(self, entity: ResiduoEspecifico) -> ResiduoEspecifico: ...
    @abstractmethod
    def update(self, id: int, entity: ResiduoEspecifico) -> ResiduoEspecifico: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...


class OperarioRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[Operario]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Optional[Operario]: ...
    @abstractmethod
    def create(self, entity: Operario) -> Operario: ...
    @abstractmethod
    def update(self, id: int, entity: Operario) -> Operario: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...


class GeneracionResiduoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[GeneracionResiduo]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Optional[GeneracionResiduo]: ...
    @abstractmethod
    def create(self, entity: GeneracionResiduo) -> GeneracionResiduo: ...
    @abstractmethod
    def update(self, id: int, entity: GeneracionResiduo) -> GeneracionResiduo: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...


class CentroCostoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[CentroCosto]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Optional[CentroCosto]: ...
    @abstractmethod
    def create(self, entity: CentroCosto) -> CentroCosto: ...
    @abstractmethod
    def update(self, id: int, entity: CentroCosto) -> CentroCosto: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...


class RolAdministrativoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[RolAdministrativo]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Optional[RolAdministrativo]: ...
    @abstractmethod
    def create(self, entity: RolAdministrativo) -> RolAdministrativo: ...
    @abstractmethod
    def update(self, id: int, entity: RolAdministrativo) -> RolAdministrativo: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...




class ActaRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[Acta]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Optional[Acta]: ...
    @abstractmethod
    def create(self, entity: Acta) -> Acta: ...
    @abstractmethod
    def update(self, id: int, entity: Acta) -> Acta: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...


class ActaGeneracionResiduoRepository(ABC):
    @abstractmethod
    def list_all(self) -> List[ActaGeneracionResiduo]: ...
    @abstractmethod
    def get_by_id(self, id: int) -> Optional[ActaGeneracionResiduo]: ...
    @abstractmethod
    def create(self, entity: ActaGeneracionResiduo) -> ActaGeneracionResiduo: ...
    @abstractmethod
    def update(self, id: int, entity: ActaGeneracionResiduo) -> ActaGeneracionResiduo: ...
    @abstractmethod
    def delete(self, id: int) -> None: ...
