# Generated by Django 5.2 on 2025-10-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(unique=True)),
                ('fecha_acta', models.DateTimeField()),
                ('documento_entrega', models.CharField()),
                ('documento_recepcion', models.CharField()),
            ],
            options={
                'db_table': 'Acta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActaGeneracionResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_reportado', models.TextField(blank=True, null=True)),
                ('peso_conciliado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Acta_GeneracionResiduo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'Area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'CategoriaResiduo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField()),
                ('nombre', models.CharField(blank=True, null=True)),
                ('clase_movimiento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CentroCosto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneracionResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('peso', models.TextField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, null=True)),
                ('motivo_otro', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GeneracionResiduo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('apellido', models.CharField(blank=True, null=True)),
                ('documento', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Operario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'Procedencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResiduoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'ResiduoEspecifico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'RolAdministrativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'Sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': 'SubArea',
                'managed': False,
            },
        ),
    ]
