# Generated by Django 5.2 on 2025-11-05 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='actageneracionresiduo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoriaresiduo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='centrocosto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='generacionresiduo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='operario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='procedencia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='residuoespecifico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roladministrativo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subarea',
            options={},
        ),
        migrations.CreateModel(
            name='NovedadConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('acta_generacion_residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='app.actageneracionresiduo')),
            ],
            options={
                'db_table': 'NovedadConciliacion',
            },
        ),
    ]
