# Generated by Django 5.2 on 2025-11-13 20:51

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_acta_options_and_more'),
    ]

    operations = [
       migrations.AddField(
            model_name='generacionresiduo',
            name='residuo_otro',
            field=models.CharField(max_length=150, blank=True, null=True),
        ),  
        
    ]
