# Generated by Django 5.2 on 2025-11-20 20:44

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_residuo_otro'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='fecha_conciliacion',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]