# Generated by Django 5.2 on 2025-11-25 20:22

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_fecha_conciliacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='consecutivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='numero_inventario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
