# Generated by Django 5.2 on 2025-11-27 14:18

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_numero_acta_and_conciliacion'),
    ]

    operations = [
         migrations.CreateModel(
            name='NumeracionActas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('ultimo_numero', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'NumeracionActas',
            },
        ),
    ]
